# CONNERY FAMILY HISTORY | GNUCLAD SETTINGS

# Not all config options are used. For a detailed list, consult the gnuclad manual.

infoBoxTitle = Family History of Connery Outfits
infoBoxTitleSize = 32
infoBoxText = <tspan style='font-weight:bold'>Version 0.6</tspan>
infoBoxText = Published under the GNU Free Documentation License
infoBoxText = Original source: Varunda's Outfit History Spreadsheet
infoBoxText = Additional data: wt.honu.pw
infoBoxTextSize = 16
infoBoxFont = Liberation Sans, Arial, Helvetica
infoBoxFontColor = #000
infoBoxColor1 = #b9d5ff
infoBoxColor2 = #70b3f2
infoBoxX = 1500
infoBoxY = 300
infoBoxWidth = 610
infoBoxHeight = 135

# Slice one node name with children, ignore the rest.
#slice =

# Correction factor for font pixel width/height. See gnuclad manual
fontCorrectionFactor = 1.0
# Orientation for the timeline; 0 - LtR, 1 - RtL, 2 - TtB, 3 - BtT
orientation = 0
# Tree layout; 0 - Branch to both sides, 1 - Branch to lower side only, 2 - Branch to lower side (inverse)
treeMode = 1
# Presorting; 0 - No sorting, 1 - By name, 2 - By start date
sortKey = 0
# Numerical format "xy"; x - Individual nodes, y - trees. See gnuclad manual
optimise = 20
# Optimization overlap setting; 0 - Allow, 1 - Forbid
strictOverlaps = 1
# How much space (in offsets) to add before/after trees
treeSpacing = 2
# How big (total children) a tree has to be before it gets spaced
treeSpacingBiggerThan = 5
# Chart background color
mainBackground = #fff
# Line width for year markers in px
rulerWidth = 2
# Line color for year markers
rulerColor = #e1e1e1
# Line width for month markers in px (0 to disable)
rulerMonthWidth = 0
# Line color for month markers
rulerMonthColor = #f0f0f0

# Width of all node lines in px
lineWidth = 4
# No. of pixels per "offset"
offsetPX = 22
# Length of fadeout region for stop dates in px (0 for abrupt stop)
stopFadeOutPX = 25
# Minimum time distance between the stop of one node and the start of another
stopSpacing = 0.4
# Distance between year markers in px
yearPX = 150

# Font for all node labels
labelFont = Liberation Sans, Arial, Helvetica
# Font size of node labels
labelFontSize = 14
# Color of label text
labelFontColor = #000
# Opacity of label backgrounds
labelBGOpacity = 40
# Optimization for strict use of ASCII characters (bool)
asciiStrings = 1
#Useful if you want to use the renames only as version bumps; 0 - rename above the dot to the right, like the first name, 1 - rename centered within the dot
nameChangeType = 0

# Shape of branches where they deviate from a parent; 0 - orthogonal, 1 - from parent's start date, 2 - diagonal, 3 - 1-year wide curve, 4 - quadraticly scaled curve, 5 - curved from parent's start date
derivType = 3
# Size of node dots in px
dotRadius = 7
# Size of small node dots in px
smallDotRadius = 5
# 0 - filled dot, 1 - hollow dot
dotType = 0
# Specifies the amount a node's line thickness should increase relative to the count of it's children. (recommended 0.0 - 1.0)
bigParent = 0.4

# Adds small half-circles to connector starting points
connectorDots = 1
# 0 - connectors are full lines, 1 - connectors have a dashed stroke
connectorsDashed = 1

# Customise the year line encompassing the cladogram
yearLinePX = 40
yearLineColor1 = #00316e
yearLineColor2 = #2c72c7
yearLineFont = Liberation Sans, Arial, Helvetica
yearLineFontSize = 22
yearLineFontColor = #fff
# How many (empty) years to append to end of chart
appendYears = 1
# How many (empty) years to append to start of chart
prependYears = 0

# Remember to adjust your input data after changing these averages.
daysInMonth = 30
monthsInYear = 12

# Not setting endOfTime will use the current date.
#endOfTime = 2012.12

# How the description field should be used; 0 - ignore, 1 - weblink URL
descriptionType = 0

# Show debug information when running gnuclad (bool)
debug = 1
